# Generated by Django 6.1.1 on 2026-09-05 15:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('heure_ouverture', models.TimeField()),
                ('heure_fermeture', models.TimeField()),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('FERMEE', 'Fermée')], default='FERMEE', max_length=20)),
            ],
            options={
                'db_table': 'caisse',
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=80)),
                ('postnom', models.CharField(blank=True, max_length=80, null=True)),
                ('prenom', models.CharField(max_length=80)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=150, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_eleves/')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'eleve',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('specialite', models.CharField(blank=True, max_length=150, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'enseignant',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'matiere',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='ModeleBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('version', models.PositiveIntegerField(default=1)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'modele_bulletin',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('ordre', models.PositiveIntegerField(unique=True)),
                ('est_ecole_base', models.BooleanField(default=False, verbose_name="Appartient à l'école de base")),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'niveau',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('CLOTUREE', 'Clôturée'), ('VERROUILLEE', 'Verrouillée')], default='OUVERTE', max_length=20)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('date_cloture', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'periode',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('libelle', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='ResponsableLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('postnom', models.CharField(blank=True, max_length=80, null=True)),
                ('prenom', models.CharField(max_length=80)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'responsable_legal',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'section',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='TypeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('libelle', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'type_action',
            },
        ),
        migrations.CreateModel(
            name='TypeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('libelle', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'type_notification',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('postnom', models.CharField(blank=True, max_length=80, null=True)),
                ('prenom', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='photos_profils/')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('seuil_passage', models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('ACTIVE', 'Active'), ('CLOTUREE', 'Clôturée')], default='PLANIFIEE', max_length=20)),
            ],
            options={
                'db_table': 'annee_scolaire',
                'ordering': ['-date_debut'],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__gt', models.F('date_debut'))), name='ck_annee_dates')],
            },
        ),
        migrations.CreateModel(
            name='CalendrierFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('modifiable', models.BooleanField(default=True)),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('CLOTURE', 'Clôturé')], default='OUVERT', max_length=20)),
                ('annee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='calendrier_financier', to='Gestion.anneescolaire')),
            ],
            options={
                'db_table': 'calendrier_financier',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=150)),
                ('actif', models.BooleanField(default=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='Gestion.anneescolaire')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='Gestion.niveau')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='Gestion.section')),
            ],
            options={
                'db_table': 'classe',
                'ordering': ['niveau__ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AffectationMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures_par_semaine', models.PositiveIntegerField(default=1)),
                ('actif', models.BooleanField(default=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_matieres', to='Gestion.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_classes', to='Gestion.matiere')),
            ],
            options={
                'db_table': 'affectation_matiere',
                'ordering': ['classe', 'matiere'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut_journee', models.TimeField(verbose_name='Heure de début de la journée')),
                ('duree_heure', models.PositiveSmallIntegerField(verbose_name="Durée d'une heure de cours")),
                ('nombre_heures_par_jour', models.PositiveSmallIntegerField(verbose_name="Nombre d'heures de cours par jour")),
                ('pause_apres_heure', models.PositiveSmallIntegerField(verbose_name="La pause intervient après l'heure")),
                ('duree_pause', models.PositiveSmallIntegerField(verbose_name='Durée de la pause')),
                ('verrouillee', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='configuration_horaire', to='Gestion.anneescolaire')),
            ],
            options={
                'verbose_name': 'Configuration horaire',
                'verbose_name_plural': 'Configurations horaires',
                'db_table': 'configuration_horaire',
            },
        ),
        migrations.CreateModel(
            name='CreneauHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField()),
                ('type_creneau', models.CharField(choices=[('COURS', 'Cours'), ('PAUSE', 'Pause')], max_length=10)),
                ('numero_heure', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('actif', models.BooleanField(default=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creneaux', to='Gestion.configurationhoraire')),
            ],
            options={
                'db_table': 'creneau_horaire',
                'ordering': ['configuration', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('affectation_matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations_enseignants', to='Gestion.affectationmatiere')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='Gestion.enseignant')),
            ],
            options={
                'db_table': 'affectation',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('date_examen', models.DateField()),
                ('bareme', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('coefficient', models.DecimalField(decimal_places=2, default=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('CLOTURE', 'Clôturé'), ('VERROUILLE', 'Verrouillé')], default='OUVERT', max_length=20)),
                ('verrouille', models.BooleanField(default=False)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examens', to='Gestion.affectation')),
            ],
            options={
                'db_table': 'examen',
            },
        ),
        migrations.CreateModel(
            name='FraisScolaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('actif', models.BooleanField(default=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frais_scolaires', to='Gestion.anneescolaire')),
            ],
            options={
                'db_table': 'frais_scolaires',
            },
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.PositiveSmallIntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi')])),
                ('salle', models.CharField(blank=True, max_length=100, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horaires', to='Gestion.affectation')),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horaires', to='Gestion.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horaires', to='Gestion.classe')),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horaires', to='Gestion.creneauhoraire')),
            ],
            options={
                'db_table': 'horaire',
                'ordering': ['jour_semaine', 'creneau__ordre'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('type_inscription', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('REINSCRIPTION', 'Réinscription')], default='NOUVELLE', max_length=20)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('ANNULEE', 'Annulée'), ('TERMINEE', 'Terminée'), ('ABANDON', 'Abandon')], default='ACTIVE', max_length=20)),
                ('bulletin_precedent_verifie', models.BooleanField(default=False)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='Gestion.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='Gestion.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='Gestion.eleve')),
            ],
            options={
                'db_table': 'inscription',
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('VERROUILLE', 'Verrouillé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins', to='Gestion.inscription')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins', to='Gestion.modelebulletin')),
            ],
            options={
                'db_table': 'bulletin',
            },
        ),
        migrations.CreateModel(
            name='LigneBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('points_max', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rang', models.PositiveIntegerField(blank=True, null=True)),
                ('appreciation', models.CharField(blank=True, max_length=255, null=True)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='Gestion.bulletin')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_bulletin', to='Gestion.matiere')),
            ],
            options={
                'db_table': 'ligne_bulletin',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('ENREGISTRE', 'Enregistré'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='ENREGISTRE', max_length=20)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='Gestion.inscription')),
            ],
            options={
                'db_table': 'paiement',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('date_evaluation', models.DateField()),
                ('bareme', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('CLOTUREE', 'Clôturée'), ('VERROUILLEE', 'Verrouillée')], default='OUVERTE', max_length=20)),
                ('verrouillee', models.BooleanField(default=False)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='Gestion.affectation')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='Gestion.periode')),
            ],
            options={
                'db_table': 'evaluation',
                'ordering': ['date_evaluation', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Proclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_proclamation', models.CharField(choices=[('PERIODE_1', 'Période 1'), ('SEMESTRE_1', 'Semestre 1'), ('PERIODE_3', 'Période 3'), ('ANNUELLE', 'Annuelle')], max_length=30)),
                ('date_proclamation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validée'), ('ANNULEE', 'Annulée')], default='VALIDE', max_length=20)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proclamations', to='Gestion.anneescolaire')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proclamations', to='Gestion.inscription')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proclamations', to='Gestion.utilisateur')),
            ],
            options={
                'db_table': 'proclamation',
            },
        ),
        migrations.AddField(
            model_name='bulletin',
            name='proclamation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins', to='Gestion.proclamation'),
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recu', models.CharField(max_length=50, unique=True)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='VALIDE', max_length=20)),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recu', to='Gestion.paiement')),
            ],
            options={
                'db_table': 'recu',
            },
        ),
        migrations.CreateModel(
            name='RepartitionHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi')], max_length=15)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repartitions_horaires', to='Gestion.affectation')),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repartitions_horaires', to='Gestion.creneauhoraire')),
            ],
            options={
                'db_table': 'repartition_horaire',
                'ordering': ['jour', 'creneau__ordre'],
            },
        ),
        migrations.CreateModel(
            name='ResponsabiliteScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_responsabilite', models.CharField(choices=[('PERE', 'Père'), ('MERE', 'Mère'), ('TUTEUR', 'Tuteur'), ('AUTRE', 'Autre')], max_length=30)),
                ('principal', models.BooleanField(default=False)),
                ('autorise_notification', models.BooleanField(default=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsabilites', to='Gestion.eleve')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='Gestion.responsablelegal')),
            ],
            options={
                'db_table': 'responsabilite_scolaire',
            },
        ),
        migrations.CreateModel(
            name='ResultatAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_semestre_1', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('points_semestre_2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('points_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('points_max', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pourcentage', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('decision', models.CharField(blank=True, choices=[('ADMIS', 'Admis'), ('AJOURNE', 'Ajourné'), ('REDOUBLE', 'Redouble'), ('ABANDON', 'Abandon')], max_length=30, null=True)),
                ('statut', models.CharField(default='CALCULE', max_length=20)),
                ('verrouille', models.BooleanField(default=False)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats_annuels', to='Gestion.anneescolaire')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats_annuels', to='Gestion.inscription')),
            ],
            options={
                'db_table': 'resultat_annuel',
            },
        ),
        migrations.CreateModel(
            name='ResultatEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_obtenus', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('verrouille', models.BooleanField(default=False)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats', to='Gestion.evaluation')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats_evaluation', to='Gestion.inscription')),
            ],
            options={
                'db_table': 'resultat_evaluation',
            },
        ),
        migrations.CreateModel(
            name='ResultatExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_obtenus', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('verrouille', models.BooleanField(default=False)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats', to='Gestion.examen')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats_examen', to='Gestion.inscription')),
            ],
            options={
                'db_table': 'resultat_examen',
            },
        ),
        migrations.CreateModel(
            name='ResultatPeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_obtenus', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('points_max', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('pourcentage', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('statut', models.CharField(default='CALCULE', max_length=20)),
                ('verrouille', models.BooleanField(default=False)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats_periode', to='Gestion.inscription')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats', to='Gestion.periode')),
            ],
            options={
                'db_table': 'resultat_periode',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='Gestion.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='Gestion.role')),
            ],
            options={
                'db_table': 'role_permission',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationPonderation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unite_n', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('poids_periode', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('poids_examen', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('poids_semestre', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ponderations', to='Gestion.anneescolaire')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ponderations', to='Gestion.matiere')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ponderations', to='Gestion.section')),
            ],
            options={
                'db_table': 'configuration_ponderation',
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('CLOTURE', 'Clôturé'), ('VERROUILLE', 'Verrouillé')], default='OUVERT', max_length=20)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semestres', to='Gestion.anneescolaire')),
            ],
            options={
                'db_table': 'semestre',
            },
        ),
        migrations.CreateModel(
            name='ResultatSemestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_periode_1', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('points_periode_2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('points_examen', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('points_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('points_max', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pourcentage', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('statut', models.CharField(default='CALCULE', max_length=20)),
                ('verrouille', models.BooleanField(default=False)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats_semestre', to='Gestion.inscription')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats', to='Gestion.semestre')),
            ],
            options={
                'db_table': 'resultat_semestre',
            },
        ),
        migrations.AddField(
            model_name='periode',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodes', to='Gestion.semestre'),
        ),
        migrations.AddField(
            model_name='examen',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examens', to='Gestion.semestre'),
        ),
        migrations.CreateModel(
            name='Titularisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=20)),
                ('date_attribution', models.DateTimeField(auto_now_add=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titularisations', to='Gestion.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titularisations', to='Gestion.classe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titularisations', to='Gestion.enseignant')),
            ],
            options={
                'db_table': 'titularisation',
            },
        ),
        migrations.CreateModel(
            name='Tranche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_echeance', models.DateField()),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tranches', to='Gestion.fraisscolaires')),
            ],
            options={
                'db_table': 'tranche',
            },
        ),
        migrations.AddField(
            model_name='paiement',
            name='tranche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='Gestion.tranche'),
        ),
        migrations.CreateModel(
            name='SortieCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('motif', models.CharField(max_length=255)),
                ('date_sortie', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('ENREGISTREE', 'Enregistrée'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], default='ENREGISTREE', max_length=20)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sorties', to='Gestion.caisse')),
                ('execute_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sorties_caisse_executees', to='Gestion.utilisateur')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sorties_caisse_validees', to='Gestion.utilisateur')),
            ],
            options={
                'db_table': 'sortie_caisse',
            },
        ),
        migrations.CreateModel(
            name='SignatureBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(max_length=100)),
                ('date_signature', models.DateTimeField(auto_now_add=True)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='Gestion.bulletin')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures_bulletin', to='Gestion.utilisateur')),
            ],
            options={
                'db_table': 'signature_bulletin',
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_presence', models.DateField()),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('RETARD', 'En retard'), ('JUSTIFIE', 'Justifié')], max_length=20)),
                ('justification', models.CharField(blank=True, max_length=255, null=True)),
                ('horaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences', to='Gestion.horaire')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences', to='Gestion.inscription')),
                ('saisi_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences_saisies', to='Gestion.utilisateur')),
            ],
            options={
                'db_table': 'presence',
            },
        ),
        migrations.AddField(
            model_name='paiement',
            name='enregistre_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_enregistres', to='Gestion.utilisateur'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements_valides', to='Gestion.utilisateur'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('A_ENVOYER', 'À envoyer'), ('ENVOYEE', 'Envoyée'), ('ECHEC', 'Échec'), ('LUE', 'Lue')], default='A_ENVOYER', max_length=20)),
                ('type_notification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='Gestion.typenotification')),
                ('utilisateur_createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications_creees', to='Gestion.utilisateur')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_cible', models.CharField(blank=True, max_length=100, null=True)),
                ('id_cible', models.PositiveIntegerField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('ancienne_valeur', models.TextField(blank=True, null=True)),
                ('nouvelle_valeur', models.TextField(blank=True, null=True)),
                ('motif', models.CharField(blank=True, max_length=500, null=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('type_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiques', to='Gestion.typeaction')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historiques', to='Gestion.utilisateur')),
            ],
            options={
                'db_table': 'historique_action',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='EntreeCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_entree', models.DateTimeField(auto_now_add=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrees', to='Gestion.caisse')),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrees_caisse', to='Gestion.paiement')),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrees_caisse_enregistrees', to='Gestion.utilisateur')),
            ],
            options={
                'db_table': 'entree_caisse',
            },
        ),
        migrations.AddField(
            model_name='enseignant',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='enseignant', to='Gestion.utilisateur'),
        ),
        migrations.CreateModel(
            name='DestinataireNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('lu', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinataires', to='Gestion.notification')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications_recues', to='Gestion.responsablelegal')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications_recues', to='Gestion.utilisateur')),
            ],
            options={
                'db_table': 'destinataire_notification',
            },
        ),
        migrations.CreateModel(
            name='DemandeAutorisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(max_length=50)),
                ('table_cible', models.CharField(max_length=100)),
                ('id_cible', models.PositiveIntegerField()),
                ('motif', models.CharField(max_length=500)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVEE', 'Approuvée'), ('REFUSEE', 'Refusée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('commentaire_decision', models.CharField(blank=True, max_length=500, null=True)),
                ('utilisateur_demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_autorisation', to='Gestion.utilisateur')),
                ('utilisateur_validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions_autorisation', to='Gestion.utilisateur')),
            ],
            options={
                'db_table': 'demande_autorisation',
            },
        ),
        migrations.CreateModel(
            name='CompteUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('mot_de_passe_hash', models.CharField(max_length=500)),
                ('echecs_connexion', models.PositiveIntegerField(default=0)),
                ('verrouille_jusqu_a', models.DateTimeField(blank=True, null=True)),
                ('dernier_login', models.DateTimeField(blank=True, null=True)),
                ('changement_mdp_obligatoire', models.BooleanField(default=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte', to='Gestion.utilisateur')),
            ],
            options={
                'db_table': 'compte_utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_anomalie', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=1000)),
                ('gravite', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=20)),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_COURS', 'En cours'), ('RESOLUE', 'Résolue'), ('IGNOREE', 'Ignorée')], default='OUVERTE', max_length=20)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anomalies_traitees', to='Gestion.utilisateur')),
            ],
            options={
                'db_table': 'anomalie',
            },
        ),
        migrations.CreateModel(
            name='Abandon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_abandon', models.DateField()),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('DECLARE', 'Déclaré'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='DECLARE', max_length=20)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='abandon', to='Gestion.inscription')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abandons_valides', to='Gestion.utilisateur')),
            ],
            options={
                'db_table': 'abandon',
            },
        ),
        migrations.CreateModel(
            name='UtilisateurRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attribution', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributions_utilisateurs', to='Gestion.role')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions_roles', to='Gestion.utilisateur')),
            ],
            options={
                'db_table': 'utilisateur_role',
            },
        ),
        migrations.AddConstraint(
            model_name='creneauhoraire',
            constraint=models.UniqueConstraint(fields=('configuration', 'ordre'), name='uq_configuration_creneau_ordre'),
        ),
        migrations.AddConstraint(
            model_name='affectation',
            constraint=models.UniqueConstraint(fields=('enseignant', 'affectation_matiere'), name='uq_enseignant_affectation_matiere'),
        ),
        migrations.AddConstraint(
            model_name='horaire',
            constraint=models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('annee', 'classe', 'jour_semaine', 'creneau'), name='uq_horaire_actif_classe_jour_creneau'),
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(fields=('eleve', 'annee'), name='uq_inscription_eleve_annee'),
        ),
        migrations.AddConstraint(
            model_name='lignebulletin',
            constraint=models.UniqueConstraint(fields=('bulletin', 'matiere'), name='uq_ligne_bulletin_matiere'),
        ),
        migrations.AddConstraint(
            model_name='affectationmatiere',
            constraint=models.UniqueConstraint(fields=('classe', 'matiere'), name='uq_affectation_classe_matiere'),
        ),
        migrations.AddConstraint(
            model_name='bulletin',
            constraint=models.UniqueConstraint(fields=('proclamation', 'inscription'), name='uq_bulletin_proclamation_inscription'),
        ),
        migrations.AddConstraint(
            model_name='repartitionhoraire',
            constraint=models.UniqueConstraint(fields=('affectation', 'jour', 'creneau'), name='uq_repartition_affectation_jour_creneau'),
        ),
        migrations.AddConstraint(
            model_name='responsabilitescolaire',
            constraint=models.UniqueConstraint(fields=('eleve', 'responsable'), name='uq_responsabilite_eleve_responsable'),
        ),
        migrations.AddConstraint(
            model_name='responsabilitescolaire',
            constraint=models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('eleve',), name='uq_responsable_principal_eleve'),
        ),
        migrations.AddConstraint(
            model_name='resultatannuel',
            constraint=models.UniqueConstraint(fields=('annee', 'inscription'), name='uq_resultat_annuel'),
        ),
        migrations.AddConstraint(
            model_name='resultatevaluation',
            constraint=models.UniqueConstraint(fields=('evaluation', 'inscription'), name='uq_resultat_evaluation'),
        ),
        migrations.AddConstraint(
            model_name='resultatexamen',
            constraint=models.UniqueConstraint(fields=('examen', 'inscription'), name='uq_resultat_examen'),
        ),
        migrations.AddConstraint(
            model_name='resultatperiode',
            constraint=models.UniqueConstraint(fields=('periode', 'inscription'), name='uq_resultat_periode'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='uq_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(fields=('annee', 'code'), name='uq_classe_annee_code'),
        ),
        migrations.AddConstraint(
            model_name='semestre',
            constraint=models.UniqueConstraint(fields=('annee', 'numero'), name='uq_semestre_annee_numero'),
        ),
        migrations.AddConstraint(
            model_name='semestre',
            constraint=models.CheckConstraint(condition=models.Q(('numero__in', [1, 2])), name='ck_semestre_numero'),
        ),
        migrations.AddConstraint(
            model_name='resultatsemestre',
            constraint=models.UniqueConstraint(fields=('semestre', 'inscription'), name='uq_resultat_semestre'),
        ),
        migrations.AddConstraint(
            model_name='periode',
            constraint=models.UniqueConstraint(fields=('semestre', 'numero'), name='uq_periode_semestre_numero'),
        ),
        migrations.AddConstraint(
            model_name='periode',
            constraint=models.CheckConstraint(condition=models.Q(('numero__in', [1, 2])), name='ck_periode_numero'),
        ),
        migrations.AddConstraint(
            model_name='titularisation',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'ACTIVE')), fields=('classe', 'annee'), name='uq_titularisation_classe_annee_active'),
        ),
        migrations.AddConstraint(
            model_name='titularisation',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'ACTIVE')), fields=('enseignant', 'annee'), name='uq_titularisation_enseignant_annee_active'),
        ),
        migrations.AddConstraint(
            model_name='tranche',
            constraint=models.UniqueConstraint(fields=('frais', 'numero'), name='uq_tranche_frais_numero'),
        ),
        migrations.AddConstraint(
            model_name='presence',
            constraint=models.UniqueConstraint(fields=('inscription', 'horaire', 'date_presence'), name='uq_presence'),
        ),
        migrations.AddConstraint(
            model_name='destinatairenotification',
            constraint=models.CheckConstraint(condition=models.Q(('utilisateur__isnull', False), ('responsable__isnull', False), _connector='XOR'), name='ck_destinataire_un_seul_type'),
        ),
        migrations.AddConstraint(
            model_name='utilisateurrole',
            constraint=models.UniqueConstraint(fields=('utilisateur', 'role'), name='uq_utilisateur_role'),
        ),
    ]
