# Generated by Django 6.1.1 on 2026-09-15 05:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomaineEnseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'domaine_enseignement',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='PonderationMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travaux_journaliers_max', models.PositiveIntegerField()),
                ('examen_max', models.PositiveIntegerField()),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ponderation_matiere',
            },
        ),
        migrations.RemoveField(
            model_name='signaturebulletin',
            name='bulletin',
        ),
        migrations.RemoveField(
            model_name='signaturebulletin',
            name='utilisateur',
        ),
        migrations.AlterModelOptions(
            name='bulletin',
            options={'ordering': ['annee_scolaire', 'inscription']},
        ),
        migrations.AlterModelOptions(
            name='lignebulletin',
            options={'ordering': ['ordre', 'matiere']},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={'ordering': ['domaine', 'libelle']},
        ),
        migrations.RemoveConstraint(
            model_name='bulletin',
            name='uq_bulletin_proclamation_inscription',
        ),
        migrations.RemoveConstraint(
            model_name='lignebulletin',
            name='uq_ligne_bulletin_matiere',
        ),
        migrations.RenameField(
            model_name='lignebulletin',
            old_name='appreciation',
            new_name='observation',
        ),
        migrations.AddField(
            model_name='bulletin',
            name='annee_scolaire',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='bulletins', to='Gestion.anneescolaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bulletin',
            name='application',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='conduite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='date_proclamation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='decision',
            field=models.CharField(blank=True, choices=[('', '---------'), ('PASSE', 'Passe'), ('DOUBLE', 'Double'), ('REPECHAGE', 'Repêchage'), ('A_DETERMINER', 'À déterminer')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='examen_repechage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='maximum_annuel',
            field=models.PositiveIntegerField(default=3040),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='nombre_eleves',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='numero_bulletin',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='observation_decision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='place',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='pourcentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='pourcentage_repechage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='total_annuel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='total_semestre_1',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='total_semestre_2',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lignebulletin',
            name='examen_repechage_max',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='lignebulletin',
            name='examen_repechage_obtenu',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AddField(
            model_name='lignebulletin',
            name='ordre',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lignebulletin',
            name='s1_examen_max',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lignebulletin',
            name='s1_examen_obtenu',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AddField(
            model_name='lignebulletin',
            name='s1_total_max',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lignebulletin',
            name='s1_total_obtenu',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AddField(
            model_name='lignebulletin',
            name='s1_travaux_journaliers_max',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lignebulletin',
            name='s1_travaux_journaliers_obtenu',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AddField(
            model_name='lignebulletin',
            name='s2_examen_max',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lignebulletin',
            name='s2_examen_obtenu',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AddField(
            model_name='lignebulletin',
            name='s2_total_max',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lignebulletin',
            name='s2_total_obtenu',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AddField(
            model_name='lignebulletin',
            name='s2_travaux_journaliers_max',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lignebulletin',
            name='s2_travaux_journaliers_obtenu',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AddField(
            model_name='lignebulletin',
            name='total_annuel_obtenu',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='inscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bulletin', to='Gestion.inscription'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('PROCLAME', 'Proclamé'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='lignebulletin',
            name='bulletin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='Gestion.bulletin'),
        ),
        migrations.AlterField(
            model_name='lignebulletin',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_bulletins', to='Gestion.matiere'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='lignebulletin',
            constraint=models.UniqueConstraint(fields=('bulletin', 'matiere'), name='uq_bulletin_matiere'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matieres', to='Gestion.domaineenseignement'),
        ),
        migrations.AddField(
            model_name='ponderationmatiere',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ponderation', to='Gestion.matiere'),
        ),
        migrations.AddField(
            model_name='ponderationmatiere',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ponderations', to='Gestion.niveau'),
        ),
        migrations.DeleteModel(
            name='SignatureBulletin',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='modele',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='proclamation',
        ),
        migrations.RemoveField(
            model_name='lignebulletin',
            name='points',
        ),
        migrations.RemoveField(
            model_name='lignebulletin',
            name='points_max',
        ),
        migrations.RemoveField(
            model_name='lignebulletin',
            name='pourcentage',
        ),
        migrations.RemoveField(
            model_name='lignebulletin',
            name='rang',
        ),
        migrations.AddConstraint(
            model_name='ponderationmatiere',
            constraint=models.UniqueConstraint(fields=('niveau', 'matiere'), name='uq_ponderation_niveau_matiere'),
        ),
    ]
