# Generated by Django 6.1.1 on 2026-09-15 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_domaineenseignement_ponderationmatiere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelebulletin',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modeles_bulletin', to='Gestion.niveau'),
        ),
        migrations.AddField(
            model_name='modelebulletin',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modeles_bulletin', to='Gestion.section'),
        ),
    ]
