# Generated by Django 6.1.1 on 2026-09-16 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_modelebulletin_niveau_modelebulletin_section'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ponderationmatiere',
            name='uq_ponderation_niveau_matiere',
        ),
        migrations.AddField(
            model_name='ponderationmatiere',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ponderations_matiere', to='Gestion.section'),
        ),
        migrations.AddConstraint(
            model_name='ponderationmatiere',
            constraint=models.UniqueConstraint(fields=('niveau', 'section', 'matiere'), name='uq_ponderation_niveau_section_matiere'),
        ),
    ]
