"""
Django settings for GestionScolaire project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env(nom, defaut=""):
    """Lit une variable d'environnement en tolérant l'absence."""
    return os.environ.get(nom, defaut)


# SECURITY WARNING: keep the secret key used in production secret!
# La cle est lue depuis l'environnement. Un developpement local peut la
#definir dans GestionScolaire/local_settings.py (non versionne) ou via
#la variable DJANGO_SECRET_KEY.
SECRET_KEY = _env(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-only-a-remplacer-par-une-varie-d-environnement",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env("DJANGO_DEBUG", "1") == "1"

ALLOWED_HOSTS = [
    h.strip()
    for h in _env("DJANGO_ALLOWED_HOSTS").split(",")
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Gestion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'GestionScolaire.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                'Gestion.context_processors.utilisateur_connecte',
                'Gestion.permissions.context_processors.permissions_context',
                'Gestion.permissions.context_processors.session_security_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'GestionScolaire.wsgi.application'
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR/ "media"
#===========================================================
#AUTHENTIFICATION
#===========================================================
LOGIN_URL = "/"
LOGIN_REDIRECT_URL = "/dashbord_admin/"
LOGOUT_REDIRECT_URL = "/"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': _env('DB_NAME', 'Gestion_Ecole'),
        'USER': _env('DB_USER'),
        'PASSWORD': _env('DB_PASSWORD'),
        'HOST': _env('DB_HOST'),
        'PORT': _env('DB_PORT'),
        'OPTIONS':{
            'driver': 'ODBC Driver 17 for SQL Server',
            'extra_params': 'TrustServerCertificate=yes;',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Sécurité de session
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True


# ============================================================
# REGLAGES LOCAUX (secrets)
# ============================================================
# Ce fichier est charge en DERNIER et surcharge ce qui precede.
# Il n'est PAS versionne : voir .gitignore.
# Idealement, ne pas l'utiliser et definir les variables
# d'environnement a la place.
try:
    from .local_settings import *  # noqa: F401,F403
except ImportError:
    pass
